// Code generated by gen_code. DO NOT EDIT.
package errmsg

const (
	TypeCodeSuccess = 10000
	TypeCodeFailed  = 10001
)

func GetSuccess() Resp {
	return Resp{Code: TypeCodeSuccess, Msg: TypeMsgSuccess}
}

func GetFailed() Resp {
	return Resp{Code: TypeCodeFailed, Msg: TypeMsgFailed}
}
